# Generated by Django 4.2.1 on 2023-05-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('measureUnit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ingredients', to='bakeryAdmin.measureunit')),
            ],
        ),
    ]
