# Generated by Django 4.2.1 on 2023-05-19 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0004_alter_fixedcost_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('creationAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bakeryAdmin.ingredient')),
                ('measureUnit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bakeryAdmin.measureunit')),
            ],
        ),
    ]
