# Generated by Django 4.2.1 on 2023-05-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0006_recipedetail_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='creationAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
