# Generated by Django 4.2.1 on 2023-05-22 08:32

from django.db import migrations

# Este script lo dejo porque lo creé de forma errónea
# El que sierve es 0011_auto_20230522_1539.py
class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0008_alter_recipe_deleted'),
    ]

    operations = [
    ]
