# Generated by Django 4.2.1 on 2023-05-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0009_auto_20230522_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='measureUnit',
        ),
        migrations.AlterField(
            model_name='recipedetail',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='bakeryAdmin.recipe'),
        ),
    ]
