# Generated by Django 4.2.1 on 2023-05-22 13:39

from django.db import migrations

DEFAULT_MEASURE_UNITS = (
    (1,'Kilogramo','Kg.', 'Unidad de medida kilogramo'),
    (2,'Gramo','Gr.', 'Unidad de medida gramos'),
    (3,'Litro','Lt.', 'Unidad de medida litro'),
    (4,'Mililitro','Ml.', 'Unidad de medida mililitro'),
    (5,'Unitario','U.', 'Unidad de medida unitaria'),
    (6,'Pliego','Pl.', 'Unidad de medida utilizada por ejemplo en el papel manteca'),
)

def add_measure_units(apps, schema_editor):
    MeasureUnit = apps.get_model('bakeryAdmin', 'MeasureUnit')

    MeasureUnit.objects.all().delete

    for id,title,symbol,description in DEFAULT_MEASURE_UNITS:
        measure_unit = MeasureUnit(id=id,title=title,symbol=symbol,description=description)
        measure_unit.save()

def remove_measure_units(apps, schema_editor):
    # This is used to migrate backward
    # You can remove your dog types, or just pass
    # pass

    MeasureUnit = apps.get_model('bakeryAdmin', 'MeasureUnit')
    for id,title,symbol,description in DEFAULT_MEASURE_UNITS:
        measure_unit = MeasureUnit.objects.get(id=id,title=title,symbol=symbol,description=description)
        measure_unit.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0010_remove_ingredient_measureunit_and_more'),
    ]

    operations = [
        migrations.RunPython(add_measure_units, remove_measure_units),
    ]
