# Generated by Django 4.2.1 on 2023-05-22 14:22

from django.db import migrations

def add_measure_units(apps, schema_editor):
    MeasureUnit = apps.get_model('bakeryAdmin', 'MeasureUnit')

    id = 6
    title = 'Pliego'
    symbol = 'Pl.'
    description = 'Unidad de medida utilizada por ejemplo en el papel manteca'

    if not MeasureUnit.objects.filter(id = 6).exists():
        measure_unit = MeasureUnit(id=id,title=title,symbol=symbol,description=description)
        measure_unit.save()

def remove_measure_units(apps, schema_editor):

    MeasureUnit = apps.get_model('bakeryAdmin', 'MeasureUnit')
    measure_unit = MeasureUnit.objects.get(id=6)
    measure_unit.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0011_auto_20230522_1539'),
    ]

    operations = [
        migrations.RunPython(add_measure_units, remove_measure_units),
    ]
