# Generated by Django 4.2.1 on 2023-05-22 14:34

from django.db import migrations


DEFAULT_INGREDIENTS = (
    (1,'Harina'),
    (2,'Azucar'),
    (3,'Azucar Glass'),
    (4,'Azucar morena'),
    (5,'Mantequilla'),
    (6,'Huevos'),
    (7,'Nata'),
    (8,'Leche'),
    (9,'Almidon de Maiz'),
    (10,'Coco Rallado'),
    (11,'Dulce de leche'),
    (12,'Chips chocolate'),
    (13,'Chocolate negro'),
    (14,'Chocolate blanco'),
    (15,'Cacao Amargo'),
    (16,'Nueces'),
    (17,'Pistacho'),
    (18,'Nueces'),
    (19,'Crocante de maní'),
    (20,'Aceite'),
    (21,'Zanahorias'),
    (22,'Naranjas'),
    (23,'Limones'),
    (24,'Polvo hornear'),
    (25,'Canela'),
    (26,'Nuez moscada'),
    (27,'Vainilla'),
    (28,'Queso crema'),
    (29,'Ricota'),
    (30,'Sal fina'),
    (31,'Membrillo'),
    (32,'Frutos rojos'),
    (33,'Mango'),
    (34,'Maracuya'),
    (35,'Brillo en gel'),
    (36,'Galletas María'),
    (37,'Galletas oreo'),
    (38,'Galletas chocolinas'),
    (39,'Bicarbonato de sodio'),
    (40,'Alcohol'),
    (41,'Vinagre'),
    (42,'Colorante rojo red velvet'),
    (43,'Bandejas para tortas'),
    (44,'Bandejas porciones'),
    (45,'Cajas para porciones'),
    (46,'Cajas tortas'),
    (47,'Bolsas de papel ( cookies)'),
    (48,'Bolsas celofan (porciones)'),
    (49,'Papel manteca'),
)

def add_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('bakeryAdmin', 'Ingredient')

    Ingredient.objects.all().delete

    for id,name in DEFAULT_INGREDIENTS:
        measure_unit = Ingredient(id=id,name=name)
        measure_unit.save()

def remove_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('bakeryAdmin', 'Ingredient')
    for id,name in DEFAULT_INGREDIENTS:
        measure_unit = Ingredient.objects.get(id=id,name=name)
        measure_unit.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0012_auto_20230522_1622'),
    ]

    operations = [
        migrations.RunPython(add_ingredients, remove_ingredients),
    ]
