# Generated by Django 4.2.1 on 2023-05-23 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0015_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Email no válido')]),
        ),
    ]
