# Generated by Django 4.2.1 on 2023-05-24 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0016_alter_supplier_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('creationAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bakeryAdmin.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='BuyOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('batch', models.CharField(max_length=200)),
                ('expirationDate', models.DateField()),
                ('buyOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyOrder', to='bakeryAdmin.buyorder')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bakeryAdmin.ingredient')),
                ('measureUnit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bakeryAdmin.measureunit')),
            ],
        ),
    ]
