# Generated by Django 4.2.1 on 2023-05-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0018_alter_buyorderdetail_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
