# Generated by Django 4.2.1 on 2023-05-24 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0019_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorderdetail',
            name='make',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='bakeryAdmin.make'),
            preserve_default=False,
        ),
    ]
