# Generated by Django 4.2.1 on 2023-05-25 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0021_alter_buyorderdetail_make'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('batch', models.CharField(max_length=200)),
                ('expirationDate', models.DateField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bakeryAdmin.ingredient')),
                ('make', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='bakeryAdmin.make')),
                ('measureUnit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bakeryAdmin.measureunit')),
            ],
        ),
        migrations.RenameModel(
            old_name='BuyOrder',
            new_name='SupplierInvoice',
        ),
        migrations.DeleteModel(
            name='BuyOrderDetail',
        ),
        migrations.AddField(
            model_name='supplierinvoicedetail',
            name='supplierInvoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplierInvoice', to='bakeryAdmin.supplierinvoice'),
        ),
    ]
