# Generated by Django 4.2.1 on 2023-05-25 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0022_supplierinvoicedetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('creationAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('productionOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productionOrder', to='bakeryAdmin.productionorder')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productionOrder_recipe', to='bakeryAdmin.recipe')),
            ],
        ),
    ]
