# Generated by Django 4.2.1 on 2023-05-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0025_alter_recipedetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoicedetail',
            name='quantityConsumed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
