# Generated by Django 4.2.1 on 2023-05-31 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0027_productionorder_closeddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrderConsume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('consumeDate', models.DateTimeField(auto_now_add=True)),
                ('SupplierInvoiceDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productionOrderConsume_supplierInvoiceDetail', to='bakeryAdmin.supplierinvoicedetail')),
                ('productionOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productionOrderConsume_productionOrder', to='bakeryAdmin.productionorder')),
            ],
        ),
    ]
