# Generated by Django 4.2.1 on 2023-05-31 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0028_productionorderconsume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionorderconsume',
            old_name='SupplierInvoiceDetail',
            new_name='supplierInvoiceDetail',
        ),
    ]
