# Generated by Django 4.2.1 on 2023-06-11 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0030_productionorder_canceleddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True)),
                ('quantityByRecipe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isForSell', models.BooleanField(default=False)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_recipe', to='bakeryAdmin.recipe')),
            ],
        ),
    ]
