# Generated by Django 4.2.1 on 2023-06-13 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0032_recipedetailproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantityConsumed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isForSell', models.BooleanField(default=False)),
                ('batch', models.CharField(max_length=200)),
                ('expirationDate', models.DateField()),
                ('unitCostPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_productStock', to='bakeryAdmin.product')),
            ],
        ),
    ]
