# Generated by Django 4.2.1 on 2023-06-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0033_productstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrderConsumeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('consumeDate', models.DateTimeField(auto_now_add=True)),
                ('productionOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productionOrderConsumeProduct_productionOrder', to='bakeryAdmin.productionorder')),
                ('productionStock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productionOrderConsumeProduct_productStock', to='bakeryAdmin.productstock')),
            ],
        ),
    ]
