# Generated by Django 4.2.1 on 2023-06-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0035_productstock_measureunit_productstock_unitsellprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionorderconsumeproduct',
            old_name='productionStock',
            new_name='productStock',
        ),
    ]
