# Generated by Django 4.2.1 on 2023-07-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryAdmin', '0037_product_measureunit_productstock_creationat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='utilityMultiplier',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
